-- Seed Data for Hoyba Local Discovery PWA
-- Realistic mock events for testing map views, full-text search, and RPC filtering

INSERT INTO public.events (
    id,
    title,
    description,
    original_lang,
    category,
    start_date,
    end_date,
    location_name,
    address,
    coordinates,
    cover_image_url,
    price,
    currency,
    ticket_url,
    is_published
) VALUES
(
    '11111111-1111-1111-1111-111111111111',
    '{"es": "Yoga al Amanecer frente al Mar", "en": "Sunrise Beach Yoga & Sound Healing", "fr": "Yoga au Lever du Soleil sur la Plage"}'::jsonb,
    '{"es": "Comienza tu día conectando cuerpo y mente con vista al mar caribeño. Apto para todos los niveles. Trae tu toalla o tapete.", "en": "Start your day aligning body and mind with panoramic Caribbean ocean views. All levels welcome. Bring a towel or mat.", "fr": "Commencez votre journée en connectant corps et esprit avec vue panoramique sur la mer des Caraïbes."}'::jsonb,
    'es',
    'wellness',
    date_trunc('day', now()) + interval '7 hours',
    date_trunc('day', now()) + interval '8 hours 30 minutes',
    'Punta Cocos Beach Club',
    'Playa Punta Cocos, Holbox',
    extensions.ST_SetSRID(extensions.ST_MakePoint(-87.3912, 21.5234), 4326)::extensions.geography,
    'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1080&q=80',
    15.00,
    'USD',
    'https://example.com/tickets/sunrise-yoga',
    true
),
(
    '22222222-2222-2222-2222-222222222222',
    '{"es": "Taller de Cerámica y Barro Artesanal", "en": "Artisan Clay & Pottery Workshop", "de": "Traditioneller Töpfer-Workshop"}'::jsonb,
    '{"es": "Aprende las técnicas ancestrales de modelado en barro y llévate tu propia pieza creada a mano.", "en": "Learn ancestral clay sculpting techniques and take home your very own handmade creation.", "de": "Lernen Sie traditionelle Modelliertechniken und nehmen Sie Ihr Kunstwerk mit."}'::jsonb,
    'es',
    'workshop',
    date_trunc('day', now()) + interval '11 hours',
    date_trunc('day', now()) + interval '13 hours 30 minutes',
    'Casa Mandala Studio',
    'Av. Damero esq. Tiburón Ballena, Holbox',
    extensions.ST_SetSRID(extensions.ST_MakePoint(-87.3789, 21.5276), 4326)::extensions.geography,
    'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1080&q=80',
    35.00,
    'USD',
    'https://example.com/tickets/clay-workshop',
    true
),
(
    '33333333-3333-3333-3333-333333333333',
    '{"es": "Sunset Acoustic Sessions & Mezcal Tasting", "en": "Sunset Acoustic Sessions & Mezcal Tasting"}'::jsonb,
    '{"es": "Música acústica en vivo mientras el sol se oculta en el horizonte, acompañado de degustación guiada de mezcales artesanales.", "en": "Live acoustic chill-out music while the sun dips into the sea, paired with a curated artisanal mezcal tasting.", "fr": "Session acoustique en direct au coucher du soleil accompagnée d''une dégustation de mezcal artisanal."}'::jsonb,
    'en',
    'live_music',
    date_trunc('day', now()) + interval '17 hours 30 minutes',
    date_trunc('day', now()) + interval '20 hours',
    'Alma Bar Rooftop',
    'Calle Palomino s/n, Holbox',
    extensions.ST_SetSRID(extensions.ST_MakePoint(-87.3802, 21.5291), 4326)::extensions.geography,
    'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1080&q=80',
    0.00,
    'USD',
    NULL,
    true
),
(
    '44444444-4444-4444-4444-444444444444',
    '{"es": "Tour Nocturno de Bioluminiscencia en Kayak", "en": "Night Bioluminescence Kayak Adventure"}'::jsonb,
    '{"es": "Rema bajo un cielo estrellado y sé testigo del resplandor azul de la bioluminiscencia en las tranquilas aguas de la laguna.", "en": "Paddle under a blanket of stars and witness glowing electric-blue bioluminescence in the tranquil lagoon waters."}'::jsonb,
    'es',
    'agenda',
    date_trunc('day', now()) + interval '21 hours',
    date_trunc('day', now()) + interval '23 hours',
    'Punta Mosquito Departure Point',
    'Playa Norte s/n, Holbox',
    extensions.ST_SetSRID(extensions.ST_MakePoint(-87.3621, 21.5342), 4326)::extensions.geography,
    'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1080&q=80',
    45.00,
    'USD',
    'https://example.com/tickets/bioluminescence',
    true
),
(
    '55555555-5555-5555-5555-555555555555',
    '{"es": "Noche de Ritmos Tropicales & Afro-House", "en": "Tropical Rhythms & Afro-House Beach Party"}'::jsonb,
    '{"es": "DJs internacionales tocando ritmos orgánicos descalzos en la arena con coctelería de autor y fogata nocturna.", "en": "International DJs spinning organic and afro-house beats on the sand with craft cocktails and beach bonfire."}'::jsonb,
    'en',
    'nightlife',
    date_trunc('day', now()) + interval '22 hours',
    date_trunc('day', now()) + interval '28 hours', -- 4:00 AM next day
    'The Hot Corner Beach Club',
    'Av. Tiburón Ballena esq. Calle Porfirio Díaz',
    extensions.ST_SetSRID(extensions.ST_MakePoint(-87.3795, 21.5284), 4326)::extensions.geography,
    'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1080&q=80',
    10.00,
    'USD',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;
